pipeline {
    agent any
    tools {
        maven 'maven-3.9.12'
    }

    stages {
        stage("build jar") {
            steps {
                // specifying the directory to run commands 
                dir(java-maven-app) {
                    echo "Building the app"
                    sh 'cd '
                    sh 'mvn package'
                }
                
            }
        }
         stage("build image") {
            steps {
                dir(java-maven-app) {
                    echo "Building the docker image"
                    withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                        sh 'docker build -t 192.168.0.104:8083/demo-app:jma-1.3 .'
                        sh 'echo $PASS | docker login -u $USER --password-stdin 192.168.0.104:8083'
                        sh 'docker push 192.168.0.104:8083/demo-app:jma-1.3'
                    }
                    
                }
            }
        }
        stage("deploy") {
            steps {
                echo "Deploying the app"
            }
        }
    }
}