@Library('jenkins-shared-library')_

def gv

pipeline {   
    agent any
    tools {
        maven 'maven-3.9.12'
    }

    stages {
        stage("init") {
            steps {
                script {
                    gv = load "java-maven-app/script.groovy"
                }
            }
        }
        stage("build jar") {
            steps {
                dir('java-maven-app') {
                    buildJar()
                }
            }
        }

        stage("build image") {
            steps {
                dir('java-maven-app') {
                    buildImage()
                }
            }
        }

        stage("deploy") {
            steps {
                script {
                    gv.deployImage()
                }
            }
        }               
    }
} 
